# GitHub Actions CI/CD Pipeline

## .github/workflows/build-and-test.yaml

```yaml
name: Build and Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install pytest pytest-cov black flake8 mypy
    
    - name: Lint Python code
      run: |
        flake8 backend/ --count --select=E9,F63,F7,F82 --show-source --statistics
        black backend/ --check
    
    - name: Type check Python code
      run: mypy backend/
    
    - name: Run Python tests
      run: |
        pytest backend/tests/ --cov=backend --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        flags: python
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install Node dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Lint TypeScript
      run: |
        cd frontend
        npm run lint
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build
    
    - name: Run frontend tests
      run: |
        cd frontend
        npm test -- --coverage

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: [test, security]
    if: github.event_name == 'push'
    
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./backend/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_REGISTRY }}/opendevagent-backend:${{ github.sha }}
          ${{ secrets.DOCKER_REGISTRY }}/opendevagent-backend:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/opendevagent-backend:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/opendevagent-backend:buildcache,mode=max
    
    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_REGISTRY }}/opendevagent-frontend:${{ github.sha }}
          ${{ secrets.DOCKER_REGISTRY }}/opendevagent-frontend:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/opendevagent-frontend:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/opendevagent-frontend:buildcache,mode=max
    
    - name: Build and push sandbox image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./sandbox_templates/Dockerfile.python
        push: true
        tags: |
          ${{ secrets.DOCKER_REGISTRY }}/opendevagent-sandbox:${{ github.sha }}
          ${{ secrets.DOCKER_REGISTRY }}/opendevagent-sandbox:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/opendevagent-sandbox:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/opendevagent-sandbox:buildcache,mode=max
```

## .github/workflows/deploy-staging.yaml

```yaml
name: Deploy to Staging

on:
  push:
    branches: [develop]

env:
  REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  IMAGE_VERSION: ${{ github.sha }}

jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    
    environment:
      name: staging
      url: https://staging-api.opendevagent.com
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
        aws-region: us-east-1
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Update ECS task definition (Backend)
      id: task-def-backend
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: deployment/ecs-task-definition-backend.json
        container-name: backend
        image: ${{ steps.login-ecr.outputs.registry }}/opendevagent-backend:${{ env.IMAGE_VERSION }}
    
    - name: Update ECS task definition (Frontend)
      id: task-def-frontend
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-backend.outputs.task-definition }}
        container-name: frontend
        image: ${{ steps.login-ecr.outputs.registry }}/opendevagent-frontend:${{ env.IMAGE_VERSION }}
    
    - name: Deploy to ECS (Staging)
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-frontend.outputs.task-definition }}
        service: opendevagent-backend-staging
        cluster: opendevagent-staging
        wait-for-service-stability: true
    
    - name: Run smoke tests
      run: |
        sleep 30
        curl -f https://staging-api.opendevagent.com/health || exit 1
        echo "Smoke tests passed"
    
    - name: Notify Slack
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: 'Staging deployment ${{ job.status }}'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        fields: repo,message,commit,author
```

## .github/workflows/deploy-production.yaml

```yaml
name: Deploy to Production

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true

env:
  REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    
    environment:
      name: production
      url: https://api.opendevagent.com
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: v${{ github.event.release.tag_name || github.event.inputs.version }}
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
        aws-region: us-east-1
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build and push Docker images
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.event.release.tag_name || github.event.inputs.version }}
      run: |
        docker build -t $ECR_REGISTRY/opendevagent-backend:$IMAGE_TAG ./backend
        docker push $ECR_REGISTRY/opendevagent-backend:$IMAGE_TAG
        
        docker build -t $ECR_REGISTRY/opendevagent-frontend:$IMAGE_TAG ./frontend
        docker push $ECR_REGISTRY/opendevagent-frontend:$IMAGE_TAG
    
    - name: Update ECS task definitions
      env:
        IMAGE_TAG: ${{ github.event.release.tag_name || github.event.inputs.version }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        # Update task definition JSON files
        sed -i 's|IMAGE_TAG|'$IMAGE_TAG'|g' deployment/ecs-task-definition-*.json
        sed -i 's|ECR_REGISTRY|'$ECR_REGISTRY'|g' deployment/ecs-task-definition-*.json
    
    - name: Deploy to ECS (Production)
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: deployment/ecs-task-definition-backend.json
        service: opendevagent-backend
        cluster: opendevagent-prod
        wait-for-service-stability: true
    
    - name: Create backup
      env:
        AWS_REGION: us-east-1
      run: |
        # Backup current database state
        aws efs backup-resource-mount-target \
          --file-system-id ${{ secrets.EFS_FILE_SYSTEM_ID }} \
          --region $AWS_REGION
    
    - name: Run health checks
      run: |
        sleep 30
        curl -f https://api.opendevagent.com/health || exit 1
        curl -f https://app.opendevagent.com/ || exit 1
        echo "Production health checks passed"
    
    - name: Notify success
      uses: 8398a7/action-slack@v3
      if: success()
      with:
        status: success
        text: 'Production deployment ${{ github.event.release.tag_name || github.event.inputs.version }} successful'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        fields: repo,message,commit,author
    
    - name: Rollback on failure
      if: failure()
      run: |
        echo "Initiating rollback..."
        # Revert to previous task definition
        aws ecs update-service \
          --cluster opendevagent-prod \
          --service opendevagent-backend \
          --task-definition opendevagent-backend-prod:PREVIOUS
    
    - name: Notify failure and rollback
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        text: 'Production deployment FAILED - ROLLBACK INITIATED'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        fields: repo,message,commit,author,action
```

## .github/workflows/performance-testing.yaml

```yaml
name: Performance Testing

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:

jobs:
  performance-test:
    name: Run Performance Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install load testing tools
      run: |
        pip install locust
    
    - name: Start test services
      run: |
        docker-compose -f docker-compose.test.yml up -d
        sleep 10
    
    - name: Run load tests
      run: |
        locust -f deployment/locustfile.py \
          --host=http://localhost:8000 \
          --users=100 \
          --spawn-rate=10 \
          --run-time=5m \
          --headless
    
    - name: Generate report
      if: always()
      run: |
        python deployment/generate_perf_report.py
    
    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: performance-results
        path: performance-report/

  load-test:
    name: Run K6 Load Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run k6 tests
      uses: grafana/k6-action@v0.3.0
      with:
        filename: deployment/k6-test.js
        cloud: true
      env:
        K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
```

## .github/workflows/security-scanning.yaml

```yaml
name: Security Scanning

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@master
      env:
        SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
    
    - name: SonarQube Quality Gate
      uses: SonarSource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run dependency-check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'OpenDevAgent'
        path: '.'
        format: 'SARIF'
        args: >
          --enableExperimental
    
    - name: Upload to GitHub Security
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: reports/dependency-check-report.sarif

  container-scanning:
    name: Container Image Scanning
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and scan with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'image'
        image-ref: 'opendevagent-backend:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
```

## .gitignore Updates

```
# Terraform
*.tfstate
*.tfstate.*
*.tfvars
!*.example.tfvars
.terraform/
.terraform.lock.hcl

# Kubernetes secrets
kubernetes/*secret*.yaml
kubernetes/*credentials*.yaml

# CI/CD
.github/workflows/secrets/

# Environment files
.env
.env.*
!.env.example

# Logs
*.log
logs/

# Test coverage
.coverage
htmlcov/
coverage.xml

# Performance reports
performance-report/
load-test-results/

# Docker
.docker/
docker-compose.override.yml
```
